### ISSUE TITLE
AttributeError: module diffusers has no attribute LCMScheduler

### ISSUE THREAD

**Issue by arjones** [replicate/latent-consistency-model#8]
Hi there,
I followed the instructions from the original blog post: [Generate images in one second on your Mac using a latent consistency model](https://replicate.com/blog/run-latent-consistency-model-on-mac)

And I am getting this error:

```sh
python main.py \
  "a beautiful apple floating in outer space, like a planet" \
  --steps 4 --width 512 --height 512
/Users/arjones/Projects/latent-consistency-model/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:659: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Loading pipeline components...:  14%|█████▎                               | 1/7 [00:00<00:00, 27.67it/s]
Traceback (most recent call last):
  File "/Users/arjones/Projects/latent-consistency-model/main.py", line 78, in <module>
    main()
  File "/Users/arjones/Projects/latent-consistency-model/main.py", line 58, in main
    predictor = Predictor()
                ^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/main.py", line 9, in __init__
    self.pipe = self._load_model()
                ^^^^^^^^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/main.py", line 12, in _load_model
    model = DiffusionPipeline.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 391, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 319, in get_class_obj_and_candidates
    class_obj = getattr(library, class_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arjones/Projects/latent-consistency-model/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 677, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute LCMScheduler. Did you mean: 'DDIMScheduler'?
```

The only difference is that I'm running Python 3.11

```sh
➜  Projects python3 -V
Python 3.11.6
```

I tried it using `Python 3.10.13` and got same results.

Running on **MacBook Pro 2023 / Apple M2 Max / 32 GB / Sonoma 14.0 (23A344)**

Thanks for any tip or advice

**Comment by Rigellute** [comment]
Also experiencing this.

**Comment by schram** [comment]
Same issue. Using the blog's instructions worked a week ago today. (2023/11/02) By two days ago (2023/11/07), it was no longer working, although no changes were made on my end. Haven't had much time to look into it, but there must be a component that is downloaded during runtime that has changed. Also on an M2 Mac running Python 3.11.6.

**Comment by RobertBolender** [comment]
It looks to me that `huggingface/diffusers` is the repository that is getting cloned at runtime, and the default branch has changed in such a way that it is no longer compatible with the code in the repository here.

I was able to get things running again by following the "deprecated" usage guidelines listed here:
https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/blob/main/README.md#usage-deprecated

Sample code change here:
https://github.com/replicate/latent-consistency-model/pull/9

Which the maintainers here may-or-may-not want to merge, there may be a better way to fix this.

**Comment by Rigellute** [comment]
Nice one @RobertBolender!
